services:
  backend:
    build: .
    container_name: outili_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      maildev:
        condition: service_started
      minio:
        condition: service_started
    networks:
      - outili
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: outili_postgres
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=outilidb
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - outili
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      start_period: 30s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.3.0
    container_name: outili_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - outili
    restart: unless-stopped

  maildev:
    image: maildev/maildev:2.2.1
    container_name: outili_maildev
    environment:
      - TZ=Asia/Shanghai
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "8025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - outili
    restart: always

  minio:
    image: minio/minio
    container_name: outili_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - outili

volumes:
  postgres:
  pgadmin:
  minio:

networks:
  outili:
    driver: bridge
